@rem
@rem Copyright © 2015-2021 the original authors.
@rem
@rem Licensed under the Apache License, Version 2.0 (the "License");
@rem you may not use this file except in compliance with the License.
@rem You may obtain a copy of the License at
@rem
@rem      https://www.apache.org/licenses/LICENSE-2.0
@rem
@rem Unless required by applicable law or agreed to in writing, software
@rem distributed under the License is distributed on an "AS IS" BASIS,
@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@rem See the License for the specific language governing permissions and
@rem limitations under the License.
@rem

@if "%DEBUG%"=="" @echo off
@rem ##########################################################################
@rem
@rem  Gradle startup script for Windows generated by Gradle.
@rem
@rem ##########################################################################

setlocal

set APP_HOME=%~dp0

set CLASSPATH=%APP_HOME%gradle\wrapper\gradle-wrapper.jar;%APP_HOME%gradle\wrapper\gradle-wrapper-shared.jar;%APP_HOME%gradle\wrapper\gradle-cli.jar

if not exist "%APP_HOME%gradle\wrapper\gradle-wrapper.jar" (
  echo ERROR: gradle-wrapper.jar not found under %APP_HOME%gradle\wrapper 1>&2
  exit /b 1
)

if not exist "%APP_HOME%gradle\wrapper\gradle-wrapper-shared.jar" (
  echo ERROR: gradle-wrapper-shared.jar not found under %APP_HOME%gradle\wrapper 1>&2
  exit /b 1
)

if not exist "%APP_HOME%gradle\wrapper\gradle-cli.jar" (
  echo ERROR: gradle-cli.jar not found under %APP_HOME%gradle\wrapper 1>&2
  exit /b 1
)

set JAVA_EXE=java.exe
if defined JAVA_HOME set JAVA_EXE=%JAVA_HOME%\bin\java.exe

"%JAVA_EXE%" -Dorg.gradle.appname=gradlew -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*

endlocal
