#!/usr/bin/env sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

set -eu

APP_HOME=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar:$APP_HOME/gradle/wrapper/gradle-wrapper-shared.jar:$APP_HOME/gradle/wrapper/gradle-cli.jar

if [ ! -r "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ] || [ ! -r "$APP_HOME/gradle/wrapper/gradle-wrapper-shared.jar" ] || [ ! -r "$APP_HOME/gradle/wrapper/gradle-cli.jar" ]; then
  echo "ERROR: Gradle wrapper jars not found under $APP_HOME/gradle/wrapper" >&2
  echo "Expected: gradle-wrapper.jar, gradle-wrapper-shared.jar, gradle-cli.jar" >&2
  exit 1
fi

JAVA_CMD=${JAVA_HOME:-}/bin/java
if [ ! -x "$JAVA_CMD" ]; then
  JAVA_CMD=java
fi

exec "$JAVA_CMD" \
  -Dorg.gradle.appname=gradlew \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
