{
  psiImplUtilClass="com.lsfusion.lang.psi.LSFPsiImplUtil"

  parserClass="com.lsfusion.lang.parser.LSFParser"
  parserUtilClass="com.lsfusion.lang.parser.LSFParserUtil"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="LSF"
  psiImplClassSuffix="Impl"
  psiPackage="com.lsfusion.lang.psi"
  psiImplPackage="com.lsfusion.lang.psi.impl"
 
  elementTypeHolderClass="com.lsfusion.lang.psi.LSFTypes"
  elementTypeClass="com.lsfusion.lang.psi.LSFElementType"
  elementTypeFactory = "com.lsfusion.lang.psi.LSFElementTypeFactory.create"

  tokenTypeClass="com.lsfusion.lang.psi.LSFTokenType"

  extendedPin = false

  // additional tokens
  tokens = [
    COMMENTS='COMMENTS'
    FAKETWODASHES='##'
    FAKETHREEDASHES='###'
  ]
}

script ::= moduleHeader (lazyScriptStatement*)

lazyScriptStatement ::= scriptStatement*
{
    lazy = true
    extends = "com.lsfusion.lang.psi.LSFLazyParsableElement"
}

scriptStatement ::= statement
{
    recoverWhile = "script_statement_recover"
}

simpleName ::= ID
{
    mixin="com.lsfusion.lang.psi.LSFIdImpl"
    implements="com.lsfusion.lang.psi.LSFId"
}

moduleHeader ::= MODULE moduleName SEMI
                 requireList?
                 priorityList?
                 namespaceName?
{
    pin = 2
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFModuleDeclarationImpl"
    implements="com.lsfusion.lang.psi.declarations.LSFModuleDeclaration"
    stubClass = "com.lsfusion.lang.psi.stubs.ModuleStubElement"
    elementTypeFactory = "com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
    recoverWhile = "script_statement_recover"
}

moduleName ::= simpleName;
requireList ::= REQUIRE nonEmptyModuleUsageList SEMI {pin = 1};
priorityList ::= PRIORITY nonEmptyNamespaceUsageList SEMI {pin = 1};
namespaceName ::= NAMESPACE namespaceUsage SEMI
{
    pin = 2;
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFExplicitNamespaceDeclarationImpl"
    implements="com.lsfusion.lang.psi.declarations.LSFExplicitNamespaceDeclaration"
    stubClass = "com.lsfusion.lang.psi.stubs.ExplicitNamespaceStubElement"
    elementTypeFactory = "com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
}

private statement ::=   constraintStatement
                    |	groupStatement
                    |	overrideStatement // starts with ID
                    |	classStatement
                    |	followsStatement // starts with ID
                    |	writeWhenStatement // starts with ID
                    |	explicitInterfacePropertyStatement
                    |	eventStatement
                    |	showDepStatement
                    |	globalEventStatement
                    |	aspectStatement
                    |	tableStatement
                    |	loggableStatement
                    |	indexStatement
                    |	formStatement
                    |	designStatement
                    |	windowStatement
                    |	navigatorStatement
                    |	metaCodeStatement // ?
                    |	metaCodeDeclarationStatement // ?
                    |   externalStatement
                    |	emptyStatement
                    |   stubStatement
                    
externalStatement ::= EXTERNAL (externalProperty | externalClass | externalModule | externalPropertyDraw | externalFormObject) SEMI {pin = 1}
externalProperty ::= PROPERTY nonEmptyNoContextPropertyUsageList {pin = 1} 
externalClass ::= CLASS nonEmptyClassNameList {pin = 1}
externalModule ::= MODULE nonEmptyModuleUsageList {pin = 1}
externalPropertyDraw ::= PROPERTYDRAW formUsage formPropertyDrawUsage
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.FormContext"
    methods = [resolveFormDecl]
}

externalFormObject ::= OBJECT formUsage objectUsage
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.FormContext"
    methods = [resolveFormDecl]
}

// some statements are pinned after the first token, so we need these fake rules to pin incomplete statements
stubStatement ::=
    EXTEND (CLASS | FORM | DESIGN) ID
    | CLASS (ABSTRACT | NATIVE)? ID
    | (ATSIGN | FORM | GROUP | META | DESIGN | TABLE) ID
    | WINDOW windowType ID
    {pin(".*") = 1}

private script_statement_recover ::= !statement_start
// Important ! after recover the rule should mandatory be pinned (matched)
private statement_start ::= ID | AFTER | BEFORE | HIDE | INDEX | LOGGABLE | NAVIGATOR | ON | SHOWDEP | WHEN | CONSTRAINT | EXTERNAL
                            | CLASS | ATSIGN | FORM | GROUP | META | DESIGN | TABLE | WINDOW | EXTEND | SEMI


////////////////////////////////////////////////////////////////////////////////
////////////////////////////////// CLASS STATEMENT /////////////////////////////
////////////////////////////////////////////////////////////////////////////////

classDecl ::= CLASS (ABSTRACT | NATIVE)? simpleNameWithCaption
{
     mixin = "com.lsfusion.lang.psi.declarations.impl.LSFClassDeclarationImpl"
     implements = "com.lsfusion.lang.psi.declarations.LSFClassDeclaration"
     stubClass = "com.lsfusion.lang.psi.stubs.ClassStubElement"
     elementTypeFactory = "com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
}

extendingClassDeclaration ::= EXTEND CLASS customClassUsageWrapper

customClassUsageWrapper ::= customClassUsage // for usages search filter

classStatement ::= (classDecl | extendingClassDeclaration) classInstancesAndParents {
    pin = 1
    mixin="com.lsfusion.lang.psi.extend.impl.LSFClassExtendImpl"
    implements="com.lsfusion.lang.psi.extend.LSFClassExtend"
    stubClass = "com.lsfusion.lang.psi.stubs.extend.ExtendClassStubElement"
    elementTypeFactory = "com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
}

private classInstancesAndParents ::=    LBRACE staticObjectDeclList RBRACE (classParentsList SEMI)? | (classParentsList)? SEMI {pin(".*") = 1}

classParentsList ::= COLON nonEmptyCustomClassUsageList {pin = 1}

staticObjectDeclList ::= (nonEmptyStaticObjectDeclList)?

nonEmptyStaticObjectDeclList ::= staticObjectDecl (COMMA staticObjectDecl)*

staticObjectDecl ::= simpleNameWithCaption
{mixin="com.lsfusion.lang.psi.declarations.impl.LSFStaticObjectDeclarationImpl" implements="com.lsfusion.lang.psi.declarations.LSFStaticObjectDeclaration"}

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////// GROUP STATEMENT /////////////////////////////
////////////////////////////////////////////////////////////////////////////////

groupStatement ::= GROUP simpleNameWithCaption (COLON groupUsage)? SEMI
{
    pin = 2
    implements="com.lsfusion.lang.psi.declarations.LSFGroupDeclaration"
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFGroupDeclarationImpl"
    stubClass = "com.lsfusion.lang.psi.stubs.GroupStubElement"
    elementTypeFactory = "com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
}


////////////////////////////////////////////////////////////////////////////////
//////////////////////////////// PROPERTY STATEMENT ////////////////////////////
////////////////////////////////////////////////////////////////////////////////

explicitInterfacePropertyStatement ::= explicitValuePropertyStatement
{
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFExplicitInterfacePropStatementImpl"
    implements="com.lsfusion.lang.psi.declarations.LSFExplicitInterfacePropStatement"
    stubClass="com.lsfusion.lang.psi.stubs.interfaces.ExplicitInterfaceStubElement"
    elementTypeFactory="com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
}

explicitValuePropertyStatement ::= implicitValuePropertyStatement
{
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFExplicitValuePropStatementImpl"
    implements="com.lsfusion.lang.psi.declarations.LSFExplicitValuePropStatement"
    stubClass="com.lsfusion.lang.psi.stubs.interfaces.ExplicitValueStubElement"
    elementTypeFactory="com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
}

implicitValuePropertyStatement ::= implicitInterfacePropertyStatement
{
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFImplicitValuePropStatementImpl"
    implements="com.lsfusion.lang.psi.declarations.LSFImplicitValuePropStatement"
    stubClass="com.lsfusion.lang.psi.stubs.interfaces.ImplicitValueStubElement"
    elementTypeFactory="com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
}

implicitInterfacePropertyStatement ::= propertyStatement
{
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFImplicitInterfacePropStatementImpl"
    implements="com.lsfusion.lang.psi.declarations.LSFImplicitInterfacePropStatement"
    stubClass="com.lsfusion.lang.psi.stubs.interfaces.ImplicitInterfaceStubElement"
    elementTypeFactory="com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
}

propertyStatement ::= propertyDeclaration EQUALS
                      (expressionUnfriendlyPD | propertyExpression) 
                      propertyOptions
                      << semicolonIfNeeded >>
{
    pin = 1
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFGlobalPropDeclarationImpl"
    implements="com.lsfusion.lang.psi.declarations.LSFGlobalPropDeclaration,com.lsfusion.lang.psi.context.ModifyParamContext"
    stubClass = "com.lsfusion.lang.psi.stubs.PropStubElement"
    elementTypeFactory = "com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
    methods = [ getContextModifier getContextInferrer ]
}

propertyDeclaration ::= simpleNameWithCaption (LBRAC classParamDeclareList RBRAC)?
{methods = [ resolveParamDecls ]}

paramDeclare ::= simpleName
{
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFParamDeclarationImpl"
    implements="com.lsfusion.lang.psi.declarations.LSFParamDeclaration"
}

classParamDeclare ::= (className paramDeclare) | paramDeclare
{
    implements="com.lsfusion.lang.psi.context.ClassParamDeclareContext"
    methods = [ resolveClass ensureClass ]
}

classParamDeclareList ::= (nonEmptyClassParamDeclareList)?
nonEmptyClassParamDeclareList ::= classParamDeclare (COMMA classParamDeclare)*

propertyExpression ::= ifPE
{
    implements = "com.lsfusion.lang.psi.context.LSFExpression"
    methods = [ resolveValueClass resolveParams resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames]
}

ifPE ::= orPE (IF orPE)*
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames]}

orPE ::= xorPE (OR xorPE)*
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames]}

xorPE ::= andPE (XOR andPE)*
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames]}

andPE ::= notPE (AND notPE)*
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames]}

notPE ::= (NOT notPE) | equalityPE
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames]}

equalityPE ::= relationalPE (EQ_OPERAND relationalPE)?
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames]}

relationalPE ::= additiveORPE (((LESS | GREATER | LESS_EQUALS | GREATER_EQUALS) additiveORPE) | typePropertyDefinition)?
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames]}

additiveORPE ::= additivePE (ADDOR_OPERAND additivePE)*
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames]}

additivePE ::= multiplicativePE ((PLUS | MINUS) multiplicativePE)*
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames]}

multiplicativePE ::= unaryMinusPE ((MULT | DIV) unaryMinusPE)*
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames]}

unaryMinusPE ::= (MINUS unaryMinusPE) | postfixUnaryPE
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames]}

postfixUnaryPE ::= simplePE (LSQBR uintLiteral RSQBR)?
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames]}

simplePE ::= (LBRAC propertyExpression RBRAC) | expressionPrimitive
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames]}

expressionPrimitive ::= <<fullCompoundParamDeclareCheck>> expressionFriendlyPD | exprParameterUsage
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames]}

expressionFriendlyPD ::= joinPropertyDefinition
	    |	multiPropertyDefinition
	    |	overridePropertyDefinition
	    |	ifElsePropertyDefinition
	    |	maxPropertyDefinition
	    |	casePropertyDefinition
	    |	partitionPropertyDefinition
	    |	recursivePropertyDefinition
	    |	structCreationPropertyDefinition
	    |	concatPropertyDefinition
	    |	castPropertyDefinition
	    |	sessionPropertyDefinition
	    |	signaturePropertyDefinition
	    |	literal
{
    implements = "com.lsfusion.lang.psi.context.LSFExpression"
    methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames ]
}

expressionUnfriendlyPD ::= contextIndependentPD | actionPropertyDefinition
{methods = [ resolveUnfriendValueClass resolveValueParamClasses]}

contextIndependentPD ::= dataPropertyDefinition
                    |   nativePropertyDefinition
	                |   abstractActionPropertyDefinition
                    |   abstractPropertyDefinition
	                |   formulaPropertyDefinition
	                |   groupPropertyDefinition
                    |   filterPropertyDefinition

joinPropertyDefinition ::= JOIN? propertyObject LBRAC propertyExpressionList RBRAC
{
    implements = "com.lsfusion.lang.psi.context.LSFExpression, com.lsfusion.lang.psi.context.PropertyUsageContext"
    methods = [ resolveInferredValueClass resolveParamClasses inferParamClasses getParamList getValueClassNames getValuePropertyNames ]
}

overridePropertyDefinition ::= (OVERRIDE | EXCLUSIVE) nonEmptyPropertyExpressionList
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames ]}

ifElsePropertyDefinition ::= IF propertyExpression
                                    THEN propertyExpression
                                    (ELSE propertyExpression)?   // check greedy
{
    pin = 1
    implements = "com.lsfusion.lang.psi.context.LSFExpression"
    methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames ]
}

maxPropertyDefinition ::= (MAX | MIN) nonEmptyPropertyExpressionList
{
    pin = 1
    implements = "com.lsfusion.lang.psi.context.LSFExpression"
    methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames ]
}

caseBranchBody ::= WHEN propertyExpression (THEN propertyExpression) {pin(".*") = 1}
casePropertyDefinition ::= CASE (exclusiveOverrideOption)?
                           (caseBranchBody)+
                           (ELSE propertyExpression)?
{
    pin = 1
    implements = "com.lsfusion.lang.psi.context.LSFExpression"
    methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames ]
}

multiPropertyDefinition ::= MULTI nonEmptyPropertyExpressionList (exclusiveOverrideOption)?
{
    pin = 1
    implements = "com.lsfusion.lang.psi.context.LSFExpression"
    methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames ]
}

partitionPropertyBy ::= BY nonEmptyPropertyExpressionList
partitionPropertyDefinition ::= PARTITION
                                (   (SUM | PREV)
                                |   UNGROUP propertyObject
                                    (   PROPORTION (STRICT)? ROUND LBRAC LEX_UINT_LITERAL RBRAC
                                    |   LIMIT (STRICT)?
                                    )
                                )
                                propertyExpression (partitionPropertyBy)?
                                (ORDER (DESC )? nonEmptyPropertyExpressionList)?
                                (WINDOW EXCEPTLAST)?
{
    pin = 1
    implements = "com.lsfusion.lang.psi.context.LSFExpression, com.lsfusion.lang.psi.context.PropertyUsageContext"
    methods = [ resolveInferredValueClass resolveParamClasses inferParamClasses getParamList getValueClassNames getValuePropertyNames ]
}

recursivePropertyDefinition ::= RECURSION propertyExpression STEP propertyExpression (CYCLES (YES |	NO | IMPOSSIBLE))?
{
    pin = 1
    implements = "com.lsfusion.lang.psi.context.LSFExpression"
    methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames ]
}

structCreationPropertyDefinition ::= STRUCT LBRAC nonEmptyPropertyExpressionList RBRAC
{
    pin = 1
    implements = "com.lsfusion.lang.psi.context.LSFExpression"
    methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames ]
}

castPropertyDefinition ::= builtInClassName LBRAC propertyExpression RBRAC
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames ]}

concatPropertyDefinition ::= CONCAT stringLiteral COMMA nonEmptyPropertyExpressionList
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames ]}

sessionPropertyType ::= PREV | CHANGED | SET | DROPPED | SETCHANGED | DROPCHANGED | DROPSET 
sessionPropertyDefinition ::= sessionPropertyType LBRAC propertyExpression RBRAC
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames ]}

signaturePropertyDefinition ::= (CLASS) LBRAC propertyExpression RBRAC
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames ]}

propertyExprObject ::= LSQBR EQUALS (propertyExpression | expressionUnfriendlyPD) RSQBR
{implements="com.lsfusion.lang.psi.context.ModifyParamContext" methods = [ getContextModifier getContextInferrer ] }

propertyObject ::=  propertyUsage | propertyExprObject
noContextPropertyUsage ::= propertyUsage
{implements = "com.lsfusion.lang.psi.context.PropertyUsageContext" methods = [ resolveParamClasses getParamList ]}


dataPropertyDefinition ::= DATA (dataPropertySessionModifier)? className (LBRAC classNameList RBRAC)
{
    pin(".*") = 1;
    implements = "com.lsfusion.lang.psi.context.UnfriendlyPE"
    methods = [ resolveUnfriendValueClass resolveValueParamClasses getValueParamClassNames getValueClassNames getValuePropertyNames getMigrationClassNames ]
}
dataPropertySessionModifier ::= SESSION

nativePropertyDefinition ::= NATIVE className LBRAC classNameList RBRAC
{
    pin = 1
    implements = "com.lsfusion.lang.psi.context.UnfriendlyPE"
    methods = [ resolveUnfriendValueClass resolveValueParamClasses getValueParamClassNames getValueClassNames getValuePropertyNames ]
}

abstractPropertyDefinition ::= ABSTRACT (((CASE | MULTI) (OVERRIDE | EXCLUSIVE)?) | OVERRIDE | EXCLUSIVE)? (CHECKED)? className LBRAC classNameList RBRAC
{
    implements = "com.lsfusion.lang.psi.context.UnfriendlyPE"
    methods = [ resolveUnfriendValueClass resolveValueParamClasses getValueParamClassNames getValueClassNames getValuePropertyNames ]
}

formulaPropertyDefinition ::= FORMULA (NULL)? (builtInClassName)? ((PG | MS)? stringLiteral)+
{
    pin = 1
    implements = "com.lsfusion.lang.psi.context.UnfriendlyPE"
    methods = [ resolveUnfriendValueClass resolveValueParamClasses getValueParamClassNames getValueClassNames getValuePropertyNames ]
}

groupingType ::= SUM | MAX | MIN | CONCAT | AGGR | EQUAL | LAST | NAGGR
groupPropertyBy ::= BY nonEmptyPropertyExpressionList;
orderPropertyBy ::= ORDER (DESC)? nonEmptyPropertyExpressionList 
groupPropertyDefinition ::= GROUP groupingType
		                    nonEmptyPropertyExpressionList
		                    (groupPropertyBy)?
		                    (orderPropertyBy)?
		                    (WHERE propertyExpression)?
{
    implements="com.lsfusion.lang.psi.context.ModifyParamContext, com.lsfusion.lang.psi.context.UnfriendlyPE"
    methods = [ getContextModifier getContextInferrer resolveUnfriendValueClass resolveValueParamClasses getValueParamClassNames getValueClassNames getValuePropertyNames ] 
}		                    

filterPropertyDefinition ::= (FILTER | ORDER | VIEW) groupObjectID
{
    implements = "com.lsfusion.lang.psi.context.UnfriendlyPE"
    methods = [ resolveUnfriendValueClass resolveValueParamClasses getValueParamClassNames getValueClassNames getValuePropertyNames ]
}

typeIs ::= IS | AS
typePropertyDefinition ::= typeIs className {pin = 1}


propertyOptions ::= (   IN groupUsage
                    |	persistentSetting
                    |   COMPLEX
                    |	TABLE tableUsage
                    |	shortcutSetting
                    |	asEditActionSetting
                    |	toolbarSetting
                    |	fixedCharWidthSetting
                    |	minCharWidthSetting
                    |	maxCharWidthSetting
                    |	prefCharWidthSetting
                    |	imageSetting
                    |	editKeySetting
                    |	autosetSetting
                    |	confirmSetting
                    |	regexpSetting
                    |	loggableSetting
                    |	echoSymbolsSetting
                    |	indexSetting
                    |	aggPropSetting
                    |	notNullSetting
                    |	onEditEventSetting
                    |	eventIdSetting
                    )*

shortcutSetting ::= SHORTCUT noContextPropertyUsage {pin = 1}
asEditActionSetting ::= (ASONCHANGE | ASONCHANGEWYS | ASONEDIT) noContextPropertyUsage {pin = 1}
toolbarSetting ::= TOOLBAR
persistentSetting ::= PERSISTENT
fixedCharWidthSetting ::= FIXEDCHARWIDTH intLiteral
minCharWidthSetting ::= MINCHARWIDTH intLiteral
maxCharWidthSetting ::= MAXCHARWIDTH intLiteral
prefCharWidthSetting ::= PREFCHARWIDTH intLiteral
imageSetting ::= IMAGE stringLiteral
editKeySetting ::= EDITKEY stringLiteral (SHOW | hideEditKey)?
autosetSetting ::= AUTOSET
confirmSetting ::= CONFIRM
regexpSetting ::= REGEXP stringLiteral (stringLiteral)?
loggableSetting ::= LOGGABLE
echoSymbolsSetting ::= ECHO
indexSetting ::= INDEXED
aggPropSetting ::= AGGPROP
notNullSetting ::= NOT nullOption (DELETE)? baseEvent
onEditEventSetting ::= ON (CHANGE | CHANGEWYS | EDIT) actionPropertyDefinitionBody
eventIdSetting ::= EVENTID stringLiteral

hideEditKey ::= HIDE

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////// ACTION PROPERTIES ///////////////////////////
////////////////////////////////////////////////////////////////////////////////

actionPropertyDefinition ::= ACTION
		                    (LBRAC exprParameterUsageList RBRAC)?
		                    actionPropertyDefinitionBody
{
    pin = 1
    // actually declare context, but it's pretty difficult to implement using only classes
    implements="com.lsfusion.lang.psi.context.ExtendParamContext"
    methods = [ getContextModifier getContextInferrer ]
}


abstractActionPropertyDefinition ::= ABSTRACT ACTION
                                    (   CASE (exclusiveOverrideOption)?
                                    |	MULTI (exclusiveOverrideOption )?
                                    |	LIST
                                    )?
                                    (CHECKED)?
                                    LBRAC classNameList RBRAC
{
    implements = "com.lsfusion.lang.psi.context.UnfriendlyPE"
    methods = [ resolveUnfriendValueClass resolveValueParamClasses getValueParamClassNames getValueClassNames getValuePropertyNames ]
}

// extendContextActionPDB comes before keepContextActionPDB to check assign action before exec action
actionPropertyDefinitionBody ::=    customActionPDB
                                |   extendContextActionPDB
                                |	keepContextActionPDB
{
    implements = "com.lsfusion.lang.psi.context.ActionExpression"
    methods = [ inferActionParamClasses ]
}

private extendContextActionPDB ::=  assignActionPropertyDefinitionBody
                        |	forActionPropertyDefinitionBody
                        |   whileActionPropertyDefinitionBody
                        |	changeClassActionPropertyDefinitionBody
                        |	deleteActionPropertyDefinitionBody
                        |	addObjectActionPropertyDefinitionBody

private keepContextActionPDB ::=    listActionPropertyDefinitionBody
                        |	requestInputActionPropertyDefinitionBody
                        |	execActionPropertyDefinitionBody
                        |   tryActionPropertyDefinitionBody
                        |	ifActionPropertyDefinitionBody
                        |	caseActionPropertyDefinitionBody
                        |	multiActionPropertyDefinitionBody
                        |	terminalFlowActionPropertyDefinitionBody
                        |   applyActionPropertyDefinitionBody

private customActionPDB ::= formActionPropertyDefinitionBody
                |	addFormActionPropertyDefinitionBody
                |	editFormActionPropertyDefinitionBody
                |	customActionPropertyDefinitionBody
                |   messageActionPropertyDefinitionBody
                |   asyncUpdateActionPropertyDefinitionBody
                |   seekObjectActionPropertyDefinitionBody
                |   confirmActionPropertyDefinitionBody
                |   emailActionPropertyDefinitionBody
                |	fileActionPropertyDefinitionBody
                |	evalActionPropertyDefinitionBody
                |	drillDownActionPropertyDefinitionBody
                |	focusActionPropertyDefinitionBody

formActionObjectUsage ::= objectUsage EQUALS propertyExpression {pin = 1}
formActionPropertyDefinitionBody ::=
	    FORM formUsage
		(formActionObjectList)?
        (contextFilterDefinition)?
		(initFilterDefinition)?
		(formSessionScopeLiteral)?
		(modalityTypeLiteral)?
		(CHECK)? (SHOWDROP)?
		(formPrintTypeLiteral)?
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression, com.lsfusion.lang.psi.context.FormContext"
    methods = [inferActionParamClasses resolveFormDecl]
}

contextFilterDefinition ::= CONTEXTFILTER formActionObjectUsage {pin = 1}

initFilterDefinition ::= INITFILTER formPropertyDrawUsage {pin = 1}

formActionObjectList ::= OBJECTS formActionObjectUsage (COMMA formActionObjectUsage)* {pin(".*") = 1}

customActionPropertyDefinitionBody ::= CUSTOM javaClassStringUsage (LBRAC classNameList RBRAC)?
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

javaClassStringUsage ::= stringLiteral
{
    mixin="com.lsfusion.lang.psi.references.impl.LSFJavaClassStringReferenceImpl"
    implements="com.lsfusion.lang.psi.references.LSFJavaClassStringReference"
}

addFormActionPropertyDefinitionBody ::= ADDFORM (SESSION | NESTED)? customClassUsage
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

editFormActionPropertyDefinitionBody ::= EDITFORM (SESSION | NESTED)? customClassUsage
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

addObjectActionPropertyDefinitionBody ::= ADDOBJ customClassUsage (WHERE propertyExpression)? (TO mappedPropertyExprParam)?
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ExtendParamContext, com.lsfusion.lang.psi.context.ActionExpression"
    methods = [ getContextModifier getContextInferrer inferActionParamClasses ]
}

emailActionPropertyDefinitionBody ::=
		EMAIL
		(FROM propertyExpression)?
		SUBJECT propertyExpression
		(emailRecipientTypeLiteral propertyExpression)*
		(	INLINE formEmailToObjects
		|	ATTACH emailAttachFormat (NAME propertyExpression)? formEmailToObjects
		)*
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

formEmailToObjects ::= formUsage formActionObjectList?
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.FormContext"
    methods = [resolveFormDecl]
}

confirmActionPropertyDefinitionBody ::= CONFIRM propertyExpression
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

messageActionPropertyDefinitionBody ::= MESSAGE (NO WAIT)? propertyExpression
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

asyncUpdateActionPropertyDefinitionBody ::= ASYNCUPDATE propertyExpression
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

seekObjectActionPropertyDefinitionBody ::= SEEK objectID propertyExpression
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

fileActionPropertyDefinitionBody ::= (LOADFILE | OPENFILE) propertyExpression
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

changeClassActionPropertyDefinitionBody ::= CHANGECLASS exprParameterUsage TO customClassUsage (WHERE propertyExpression)?
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ExtendParamContext, com.lsfusion.lang.psi.context.ActionExpression"
    methods = [ getContextModifier getContextInferrer inferActionParamClasses ]
}

deleteActionPropertyDefinitionBody ::= DELETE exprParameterUsage (WHERE propertyExpression)?
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ExtendParamContext, com.lsfusion.lang.psi.context.ActionExpression"
    methods = [ getContextModifier getContextInferrer inferActionParamClasses ]
}

evalActionPropertyDefinitionBody ::= EVAL propertyExpression
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

focusActionPropertyDefinitionBody ::= FOCUS formPropertyDrawID
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

drillDownActionPropertyDefinitionBody ::= DRILLDOWN propertyExpression
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

requestInputActionPropertyDefinitionBody ::= REQUEST typeId (INPUT | (ID)? actionPropertyDefinitionBody)
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

listActionPropertyDefinitionBody ::=    (
                                            (
                                                NEWSESSION (NESTED | migratePropertiesSelector)?
                                                |
                                                (NEWTHREAD uintLiteral? (DELAY uintLiteral)?)
                                            )
                                            (AUTOAPPLY)?
                                            (SINGLE)?
                                        )?
		                                LBRACE
			                            listActionStatement*
		                                RBRACE
{
    pin = 2
    mixin="com.lsfusion.lang.psi.LSFListActionImpl"
    implements="com.lsfusion.lang.psi.LSFListAction, com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

private migratePropertiesSelector ::= LBRAC (nonEmptyNoContextPropertyUsageList | MULT) RBRAC

private listActionStatement ::= (   actionPropertyDefinitionBody << semicolonIfNeeded >>  //  !} => ;
                                |   localDataPropertyDefinition SEMI
                                |   emptyStatement
                                |   stubListActionStatement
                                )
{
    pin(".*") = 1
    recoverWhile = "list_action_statement_recover"
}

private list_action_statement_recover ::= !(ADDFORM | ADDOBJ | APPLY | ASSIGN | ASYNCUPDATE | BREAK | CASE | CHANGECLASS | CONFIRM | CUSTOM | DELETE
                                            | DRILLDOWN | EDITFORM | EMAIL | EVAL | EXEC | FOR | FORM | TRY | IF | LOADFILE | LOCAL | MESSAGE | MULTI | OPENFILE
                                            | REQUEST | RETURN | SEEK | WHILE
                                            | NEWSESSION | NEWTHREAD
                                            | ID
                                            | SEMI
                                            | LBRACE
                                            | RBRACE
                                           )
                                           
stubListActionStatement ::=     (
                                    NEWSESSION (NESTED | migratePropertiesSelector)?
                                    |
                                    (NEWTHREAD uintLiteral? (DELAY uintLiteral)?)
                                )
                                (AUTOAPPLY)?
                                (SINGLE)?
                                LBRACE
{
    pin(".*") = 1
}                                           

localDataPropertyDefinition ::= LOCAL simpleName EQUALS className LBRAC classNameList RBRAC
{
    pin = 1
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFLocalPropDeclarationImpl"
    implements="com.lsfusion.lang.psi.declarations.LSFLocalPropDeclaration"
}

//Разбиваем правило, чтобы была возможность запинить по EXEC
execActionPropertyDefinitionBody ::= execActionPropertyDefinitionBody1 | execActionPropertyDefinitionBody2
{
    implements = "com.lsfusion.lang.psi.context.PropertyUsageContext, com.lsfusion.lang.psi.context.ActionExpression"
    methods = [ resolveParamClasses inferActionParamClasses getParamList ]
}
private execActionPropertyDefinitionBody1 ::= EXEC propertyObject LBRAC propertyExpressionList RBRAC {pin = 1}
//EXEC - последнее правило, которое может начинаться с ID, поэтому спокойно пиним
private execActionPropertyDefinitionBody2 ::= propertyObject LBRAC propertyExpressionList RBRAC {pin = 1}

//Разбиваем правило, чтобы была возможность запинить по ASSIGN
assignActionPropertyDefinitionBody ::= assignActionPropertyDefinitionBody1 | assignActionPropertyDefinitionBody2
{
    implements="com.lsfusion.lang.psi.context.ExtendParamContext, com.lsfusion.lang.psi.context.ActionExpression"
    methods = [ getContextModifier getContextInferrer inferActionParamClasses ]
}

private assignActionPropertyDefinitionBody1 ::= ASSIGN mappedPropertyExprParam ARROW propertyExpression (WHERE propertyExpression)? {pin = 1}
private assignActionPropertyDefinitionBody2 ::= mappedPropertyExprParam ARROW propertyExpression (WHERE propertyExpression)? {pin = 2}

tryActionPropertyDefinitionBody ::= TRY actionPropertyDefinitionBody (FINALLY actionPropertyDefinitionBody)?
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression" methods = [inferActionParamClasses]
}

ifActionPropertyDefinitionBody ::= IF propertyExpression THEN actionPropertyDefinitionBody (ELSE actionPropertyDefinitionBody)?
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression" methods = [inferActionParamClasses]
}

caseActionPropertyDefinitionBody ::= CASE (exclusiveOverrideOption)? (actionCaseBranchBody)+ (ELSE actionPropertyDefinitionBody)?
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

actionCaseBranchBody ::= WHEN propertyExpression (THEN actionPropertyDefinitionBody) {pin(".*") = 1}

multiActionPropertyDefinitionBody ::= MULTI (exclusiveOverrideOption)? nonEmptyActionPDBList
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

applyActionPropertyDefinitionBody ::= APPLY migratePropertiesSelector? SINGLE? actionPropertyDefinitionBody
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ActionExpression"
    methods = [inferActionParamClasses]
}

forAddObjClause ::= ADDOBJ (paramDeclare EQUALS)? customClassUsage
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ClassParamDeclareContext"
    methods = [ resolveClass ensureClass ]
}

forActionPropertyDefinitionBody ::= FOR (propertyExpression (ORDER (DESC)? nonEmptyPropertyExpressionList)? )?
		                            inlineStatement
		                            (forAddObjClause)?
		                            DO actionPropertyDefinitionBody
		                            (ELSE actionPropertyDefinitionBody)?
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ExtendParamContext, com.lsfusion.lang.psi.context.ActionExpression"
    methods = [ getContextModifier getContextInferrer inferActionParamClasses ]
}
                                                       
whileActionPropertyDefinitionBody ::= WHILE (propertyExpression (ORDER (DESC)? nonEmptyPropertyExpressionList)? )?
		                              inlineStatement
		                              (forAddObjClause)?
		                              DO actionPropertyDefinitionBody
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ExtendParamContext, com.lsfusion.lang.psi.context.ActionExpression"
    methods = [ getContextModifier getContextInferrer inferActionParamClasses ]
}

terminalFlowActionPropertyDefinitionBody ::= BREAK | RETURN
{
    implements="com.lsfusion.lang.psi.context.ActionExpression" methods = [inferActionParamClasses]
}

////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////// FORM STATEMENT /////////////////////////////
////////////////////////////////////////////////////////////////////////////////

formStatement ::=	(	formDecl
            		|	extendingFormDeclaration
		            )
                    (	formGroupObjectsList
                    |	formTreeGroupObjectList
                    |	formFiltersList
                    |	formPropertiesList
                    |	formHintsList
                    |	formEventsList
                    |	formFilterGroupDeclaration
                    |	formExtendFilterGroupDeclaration
                    |	formOrderByList
                    |	dialogFormDeclaration
                    |	editFormDeclaration
                    |	listFormDeclaration
                    )*
                    SEMI
{
    pin=1
    elementTypeFactory = "com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
    stubClass = "com.lsfusion.lang.psi.stubs.extend.ExtendFormStubElement"
    implements="com.lsfusion.lang.psi.extend.LSFFormExtend, com.lsfusion.lang.psi.context.FormContext"
    mixin="com.lsfusion.lang.psi.extend.impl.LSFFormExtendImpl"
    methods = [resolveFormDecl]
}

dialogFormDeclaration ::= DIALOG customClassUsage OBJECT objectUsage {pin = 1}
editFormDeclaration ::= EDIT customClassUsage OBJECT objectUsage {pin = 1}
listFormDeclaration ::= LIST customClassUsage OBJECT objectUsage {pin = 1}

formDecl ::= FORM simpleNameWithCaption
		            (TITLE stringLiteral)?
		            (modalityTypeLiteral)?
		            (IMAGE stringLiteral)?
		            (AUTOREFRESH intLiteral)?
		            (KEEPSESSIONPROPERTIES)?
{
    pin = 2
    mixin ="com.lsfusion.lang.psi.declarations.impl.LSFFormDeclarationImpl"
    implements="com.lsfusion.lang.psi.declarations.LSFFormDeclaration"
    stubClass = "com.lsfusion.lang.psi.stubs.FormStubElement"
    elementTypeFactory = "com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
}

extendingFormDeclaration ::= EXTEND FORM formUsageWrapper

formUsageWrapper ::= formUsage // for usages search filter

formGroupObjectsList ::= OBJECTS formGroupObjectDeclaration (COMMA formGroupObjectDeclaration)* {pin = 1}

formTreeGroupObjectList ::= TREE (treeGroupDeclaration)? formTreeGroupObjectDeclaration (COMMA formTreeGroupObjectDeclaration)* {pin = 1}

treeGroupDeclaration ::= simpleName
{
    implements="com.lsfusion.lang.psi.declarations.LSFTreeGroupDecl"
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFTreeGroupDeclImpl"
}

formGroupObjectDeclaration ::= formCommonGroupObject (formGroupObjectReportPath)? (formGroupObjectViewType)? (formGroupObjectPageSize)?
formTreeGroupObjectDeclaration ::= formCommonGroupObject (treeGroupParentDeclaration)?
{implements = "com.lsfusion.lang.psi.context.PropertyUsageContext" methods = [ resolveParamClasses getParamList ]}

treeGroupParentDeclaration ::= PARENT (propertyUsage | LBRAC nonEmptyPropertyUsageList RBRAC) { pin = 1 }

formCommonGroupObject ::= formSingleGroupObjectDeclaration | formMultiGroupObjectDeclaration
{mixin="com.lsfusion.lang.psi.declarations.impl.LSFGroupObjectDeclarationImpl" implements="com.lsfusion.lang.psi.declarations.LSFGroupObjectDeclaration"}

formGroupObjectReportPath ::= REPORTFILE formPropertyObject

formGroupObjectViewType ::= (INIT | FIXED) classViewType

classViewType ::= PANEL | HIDE | GRID

formGroupObjectPageSize ::= PAGESIZE intLiteral

formSingleGroupObjectDeclaration ::= formObjectDeclaration

formMultiGroupObjectDeclaration ::= (simpleName EQUALS)?
		                            LBRAC
			                        formObjectDeclaration (COMMA formObjectDeclaration)+
		                            RBRAC

formObjectDeclaration ::= (simpleName EQUALS)?
		                  className (stringLiteral)?
		                  (ON CHANGE formActionPropertyObject)?
{
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFObjectDeclarationImpl"
    implements="com.lsfusion.lang.psi.declarations.LSFObjectDeclaration"
}

formPropertyDrawNameDecl ::= (simpleName EQUALS)? formPropertyName formPropertyOptionsList
{
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFPropertyDrawNameDeclarationImpl"
    implements="com.lsfusion.lang.psi.declarations.LSFPropertyDrawNameDeclaration"
}

formPropertiesNamesDeclList ::=	formPropertyDrawNameDecl (COMMA formPropertyDrawNameDecl)*

formPropertiesList ::=  PROPERTIES (formMappedNamePropertiesList | formPropertyOptionsList formMappedPropertiesList) { pin = 1 }

formMappedNamePropertiesList ::= LBRAC objectUsageList RBRAC formPropertyOptionsList formPropertiesNamesDeclList
{
    pin = 1
    implements = "com.lsfusion.lang.psi.context.PropertyUsageContext"
    methods = [ resolveParamClasses getParamList]
}

formPropertyOptionsList ::= (    EDITABLE
                            |    READONLY
                            |    SELECTOR
                            |    HINTNOUPDATE
                            |    HINTTABLE
                            |    OPTIMISTICASYNC
                            |    formOptionToolbar
                            |    formOptionForce
                            |    formOptionToDraw
                            |    formOptionEventId
                            |    formOptionColumns
                            |    formOptionsWithCalcPropertyObject
                            |    formOptionsWithFormPropertyDraw
                            |    formOptionsOnEvents
                            )*

formOptionToolbar ::= TOOLBAR
formOptionColumns ::= COLUMNS (stringLiteral)? LBRAC nonEmptyGroupObjectUsageList RBRAC {pin = 1}
formOptionForce ::= FORCE classViewType {pin = 1}
formOptionToDraw ::= TODRAW groupObjectUsage {pin = 1}
formOptionEventId ::= EVENTID stringLiteral {pin = 1}
formOptionsWithCalcPropertyObject ::= (SHOWIF | READONLYIF | BACKGROUND | FOREGROUND | HEADER | FOOTER) formCalcPropertyObject {pin = 1}
formOptionsWithFormPropertyDraw ::= (BEFORE | AFTER | QUICKFILTER) formPropertyDrawUsage {pin = 1}
formOptionsOnEvents ::= ON (EDIT | CHANGE | CHANGEWYS | (SHORTCUT (stringLiteral)?) ) formActionPropertyObject
{
    pin = 1
}

formCalcPropertyObject ::= formPropertyObject
formActionPropertyObject ::= formPropertyObject

formPropertyDrawMappedDecl ::= (simpleName EQUALS)? formPropertyObject formPropertyOptionsList
{
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFPropertyDrawMappedDeclarationImpl"
    implements="com.lsfusion.lang.psi.declarations.LSFPropertyDrawMappedDeclaration"
}

formMappedPropertiesList ::= formPropertyDrawMappedDecl (COMMA formPropertyDrawMappedDecl)* {pin = 1}

formFiltersList ::= FILTERS formFilterDeclaration (COMMA formFilterDeclaration)* {pin(".*") = 1}

formHintsList ::= (HINTNOUPDATE | HINTTABLE) LIST nonEmptyNoContextPropertyUsageList {pin = 1}

formEventsList ::= EVENTS formEventDeclaration (COMMA formEventDeclaration)* {pin = 1}

formEventDeclaration ::= ON
                        (    OK
                        |    APPLY
                        |    CLOSE
                        |    INIT
                        |    CANCEL
                        |    DROP
                        |    QUERYOK
                        |    QUERYCLOSE
                        |    CHANGE ID
                        )
                        formActionPropertyObject
{
    pin = 1
}

formFilterGroupDeclaration ::= FILTERGROUP filterGroupName regularFilterDeclaration*
{pin = 1}

filterGroupName ::= simpleName
{
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFFilterGroupDeclarationImpl"
    implements="com.lsfusion.lang.psi.declarations.LSFFilterGroupDeclaration"
}

formExtendFilterGroupDeclaration ::= EXTEND FILTERGROUP filterGroupUsage regularFilterDeclaration+
{pin(".*") = 1}

filterGroupUsage ::= simpleName
{
    mixin="com.lsfusion.lang.psi.references.impl.LSFFilterGroupReferenceImpl"
    implements="com.lsfusion.lang.psi.references.LSFFilterGroupReference"
}

regularFilterDeclaration ::= FILTER stringLiteral stringLiteral formFilterDeclaration (filterSetDefault)?

formFilterDeclaration ::= propertyExpression
filterSetDefault ::= DEFAULT

formOrderByList ::= ORDER BY formPropertyDrawWithOrder (COMMA formPropertyDrawWithOrder)* {pin(".*") = 1}

formPropertyDrawWithOrder ::= formPropertyDrawUsage (ASC | DESC)?

predefinedFormPropertyName ::= OBJVALUE
                           |    SELECTION
                           |    ADDOBJ
                           |    ADDFORM
                           |    ADDNESTEDFORM
                           |    ADDSESSIONFORM
                           |    EDITFORM
                           |    EDITNESTEDFORM
                           |    EDITSESSIONFORM
                           |    DELETE
                           |    DELETESESSION
{
    mixin="com.lsfusion.lang.psi.LSFIdImpl"
    implements="com.lsfusion.lang.psi.LSFId"
}

formPropertyName ::= propertyUsage | predefinedFormPropertyName

formPropertyObject ::= formPropertyName LBRAC objectUsageList RBRAC
{
    pin = 1
    implements = "com.lsfusion.lang.psi.context.PropertyUsageContext"
    methods = [ resolveParamClasses getParamList ]
}

aliasUsage ::= simpleName

formPropertyDrawPropertyUsage ::= simpleName

formPropertyDrawUsage ::= (<< notSimpleIdAhead >> formPropertyDrawPropertyUsage LBRAC objectUsageList RBRAC) | aliasUsage
{
    implements="com.lsfusion.lang.psi.references.LSFPropertyDrawReference"
    mixin="com.lsfusion.lang.psi.references.impl.LSFPropertyDrawReferenceImpl"
}

////////////////////////////////////////////////////////////////////////////////
/////////////////////////////OVERRIDE STATEMENT/////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

overrideStatement ::= mappedPropertyClassParamDeclare PLUSEQ
		                (WHEN propertyExpression THEN)?
		                (	propertyExpression
		                |	actionPropertyDefinition
		                )
		                << semicolonIfNeeded >>
{
    pin = 2;
    implements="com.lsfusion.lang.psi.context.ModifyParamContext"
    methods = [ getContextModifier getContextInferrer getIcon ]
}

////////////////////////////////////////////////////////////////////////////////
//////////////////////////////// CONSTRAINT STATEMENT //////////////////////////
////////////////////////////////////////////////////////////////////////////////

constraintStatement ::= CONSTRAINT baseEvent propertyExpression
		                (CHECKED (BY nonEmptyNoContextPropertyUsageList)? )?
		                MESSAGE stringLiteral
		                SEMI
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ModifyParamContext"
    methods = [ getContextModifier getContextInferrer getIcon ]
}

////////////////////////////////////////////////////////////////////////////////
///////////////////////////////// FOLLOWS STATEMENT ////////////////////////////
////////////////////////////////////////////////////////////////////////////////

followsStatement ::= mappedPropertyClassParamDeclare FOLLOWS
                     propertyExpression (RESOLVE followsResolveType baseEvent)?
		             (COMMA propertyExpression (RESOLVE followsResolveType baseEvent)?)*
		             SEMI
{
    pin = 2
    implements="com.lsfusion.lang.psi.context.ModifyParamContext"
    methods = [ getContextModifier getContextInferrer getIcon ]
}

followsResolveType ::= LEX_LOGICAL_LITERAL | ALL | NOTHING

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////// WRITE STATEMENT /////////////////////////////
////////////////////////////////////////////////////////////////////////////////

writeWhenStatement ::= mappedPropertyClassParamDeclare ARROW propertyExpression WHEN (DO)? propertyExpression SEMI
{
    pin = 2
    implements="com.lsfusion.lang.psi.context.ModifyParamContext"
    methods = [ getContextModifier getContextInferrer getIcon ]
}

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////// EVENT STATEMENT /////////////////////////////
////////////////////////////////////////////////////////////////////////////////

eventStatement ::= WHEN baseEvent propertyExpression inlineStatement
		                DO actionPropertyDefinitionBody (ORDER (DESC)? nonEmptyPropertyExpressionList)?
		           << semicolonIfNeeded >>
{
    pin = 1
    implements="com.lsfusion.lang.psi.context.ModifyParamContext"
    methods = [ getContextModifier getContextInferrer getIcon ]
}

////////////////////////////////////////////////////////////////////////////////
//////////////////////////// GLOBAL EVENT STATEMENT ////////////////////////////
////////////////////////////////////////////////////////////////////////////////

globalEventStatement ::= ON baseEvent (SINGLE)? (SHOWDEP ID)? actionPropertyDefinitionBody << semicolonIfNeeded >>
{
    pin=1
    implements="com.lsfusion.lang.psi.context.ModifyParamContext"
    methods = [ getContextModifier getContextInferrer getIcon ]
}

baseEvent ::= (GLOBAL | SESSION)? (FORMS nonEmptyFormUsageList)? (GOAFTER nonEmptyNoContextPropertyUsageList)?

inlineStatement ::=   (NOINLINE (LBRAC exprParameterUsageList RBRAC)? )? (INLINE)?

////////////////////////////////////////////////////////////////////////////////
//////////////////////////////// SHOWDEP STATEMENT //////////////////////////////
////////////////////////////////////////////////////////////////////////////////

showDepStatement ::= SHOWDEP noContextPropertyUsage FROM noContextPropertyUsage SEMI {pin=1 methods = [ getIcon ]}

////////////////////////////////////////////////////////////////////////////////
//////////////////////////////// ASPECT STATEMENT //////////////////////////////
////////////////////////////////////////////////////////////////////////////////

aspectStatement ::= (BEFORE | AFTER) mappedPropertyClassParamDeclare DO actionPropertyDefinitionBody << semicolonIfNeeded >>
{
    pin=1
    implements="com.lsfusion.lang.psi.context.ModifyParamContext"
    methods = [ getContextModifier getContextInferrer getIcon ]
}


////////////////////////////////////////////////////////////////////////////////
////////////////////////////////// TABLE STATEMENT /////////////////////////////
////////////////////////////////////////////////////////////////////////////////

tableStatement ::= TABLE simpleName LBRAC nonEmptyClassNameList RBRAC SEMI 
{
    pin = 2
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFTableDeclarationImpl"
    implements="com.lsfusion.lang.psi.declarations.LSFTableDeclaration"
    stubClass = "com.lsfusion.lang.psi.stubs.TableStubElement"
    elementTypeFactory = "com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
}


////////////////////////////////////////////////////////////////////////////////
/////////////////////////////// LOGGABLE STATEMENT /////////////////////////////
////////////////////////////////////////////////////////////////////////////////

loggableStatement ::= LOGGABLE nonEmptyNoContextPropertyUsageList SEMI {pin=1 methods = [ getIcon ]}

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////// INDEX STATEMENT /////////////////////////////
////////////////////////////////////////////////////////////////////////////////

indexStatement ::= INDEX nonEmptyNoContextPropertyUsageList SEMI {pin=1 methods = [ getIcon ]}

////////////////////////////////////////////////////////////////////////////////
/////////////////////////////// WINDOW STATEMENT ////////////////////////////
////////////////////////////////////////////////////////////////////////////////

windowStatement ::= windowCreateStatement | windowHideStatement {pin=1 methods = [ getIcon ]}

windowCreateStatement ::= WINDOW windowType simpleName stringLiteral windowOptions SEMI
{mixin="com.lsfusion.lang.psi.declarations.impl.LSFWindowDeclarationImpl" implements="com.lsfusion.lang.psi.declarations.LSFWindowDeclaration"
    stubClass = "com.lsfusion.lang.psi.stubs.WindowStubElement"
    elementTypeFactory = "com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
    pin = 3
}

windowHideStatement ::= HIDE WINDOW windowUsage SEMI {pin=2}

windowType ::= MENU | PANEL | TOOLBAR | TREE

windowOptions ::=   (	HIDETITLE
                    |	DRAWROOT
                    |	HIDESCROLLBARS
                    |	orientation
                    |	dockPosition
                    |	borderPosition
                    |	HALIGN LBRAC alignmentLiteral RBRAC
                    |	VALIGN LBRAC alignmentLiteral RBRAC
                    |	TEXTHALIGN LBRAC alignmentLiteral RBRAC
                    |	TEXTVALIGN LBRAC alignmentLiteral RBRAC
                    )*

borderPosition ::= LEFT	| RIGHT | TOP | BOTTOM
orientation ::= VERTICAL | HORIZONTAL
dockPosition ::= POSITION LBRAC intLiteral COMMA intLiteral COMMA intLiteral COMMA intLiteral RBRAC

////////////////////////////////////////////////////////////////////////////////
/////////////////////////////// NAVIGATOR STATEMENT ////////////////////////////
////////////////////////////////////////////////////////////////////////////////

navigatorStatement ::= NAVIGATOR navigatorElementStatementBody {pin=1 methods = [ getIcon ]}

navigatorElementStatementBody ::=   (   LBRACE
                                        (	addNavigatorElementStatement
                                        |	newNavigatorElementStatement
                                        |	setupNavigatorElementStatement
                                        |	emptyStatement
                                        )*
                                        RBRACE
                                    ) | emptyStatement

addNavigatorElementStatement ::= ADD navigatorElementSelector (stringLiteral)? navigatorElementInsertPositionSelector (TO windowUsage)? navigatorElementStatementBody
{
    pin = 1
}

newNavigatorElementStatement ::= NEW simpleName (ACTION noContextPropertyUsage)? stringLiteral navigatorElementInsertPositionSelector (TO windowUsage)? (IMAGE stringLiteral)? navigatorElementStatementBody
{
    pin = 2
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFNavigatorElementDeclarationImpl"
    implements="com.lsfusion.lang.psi.declarations.LSFNavigatorElementDeclaration"
    stubClass = "com.lsfusion.lang.psi.stubs.NavigatorElementStubElement"
    elementTypeFactory = "com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
}

navigatorElementInsertPositionSelector ::=	(IN navigatorElementSelector)?
                                            (   insertRelativePositionLiteral navigatorElementSelector
                                            |	FIRST
                                            )?

setupNavigatorElementStatement ::= navigatorElementSelector (stringLiteral)? (TO windowUsage)? navigatorElementStatementBody

navigatorElementSelector ::= navigatorElementUsage

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////// DESIGN STATEMENT ////////////////////////////
////////////////////////////////////////////////////////////////////////////////

designStatement ::=	(designDeclaration | extendDesignDeclaration) componentBody {
    pin = 1
    implements = "com.lsfusion.lang.psi.context.FormContext"
    methods = [ getIcon resolveFormDecl]
}

designDeclaration ::= DESIGN formUsage (stringLiteral)? (fromDefaultStatement)? {pin=2}

fromDefaultStatement ::= FROM DEFAULT

extendDesignDeclaration ::= EXTEND DESIGN formUsage

componentBody ::= componentBlockStatement | emptyStatement

componentBlockStatement ::= LBRACE componentStatement* RBRACE
{
    pin = 1
}

componentStatement ::=      setObjectPropertyStatement
                        |	setupComponentStatement
                        |	setupGroupObject
                        |	newComponentStatement
                        |	addComponentStatement
                        |	removeComponentStatement
                        |	emptyStatement
                        |   componentStubStatement
{
    recoverWhile = "component_statement_recover"
}

private component_statement_recover ::= !component_statement_recover_start 
private component_statement_recover_start ::= ID | GROUP | PARENT | PROPERTY | NEW | ADD | REMOVE | SEMI | RBRACE 

componentStubStatement ::=      GROUP LBRAC ID RBRAC LBRACE
                            |   NEW ID
  
{
    pin(".*") = 1
}

setupComponentStatement ::= componentSelector componentBody
{
    pin = 1
}

setupGroupObject ::= GROUP LBRAC groupObjectUsage RBRAC
                           LBRACE setupGroupObjectStatement* RBRACE
{
    pin = 5
}

setupGroupObjectStatement ::=   setGroupObjectPropertyStatement
                            |   emptyStatement
{
    recoverWhile = "setup_group_object_statement_recover"
}
                                
private setup_group_object_statement_recover ::= !(ID | SEMI | RBRACE)

setGroupObjectPropertyStatement ::= ID EQUALS componentPropertyValue SEMI {pin = 1}
                              
newComponentStatement ::= NEW componentStubDecl componentInsertPositionSelector componentBody {pin = 2}
addComponentStatement ::= ADD componentSelector componentInsertPositionSelector componentBody {pin = 1}

componentInsertPositionSelector ::= (IN inPositionComponent)?
                                    (   insertRelativePositionLiteral componentSelector
                                    |	FIRST
                                    )?

removeComponentStatement ::= REMOVE componentSelector (removeCascade)? SEMI {pin = 1}
removeCascade ::= CASCADE

inPositionComponent ::= componentSelector

componentSelector ::=   PARENT LBRAC componentSelector RBRAC
                	|	PROPERTY LBRAC propertySelector RBRAC
                    |	componentUsage
{
    pin(".*") = 1
}

componentStubDecl ::= componentDecl
{
    implements="com.lsfusion.lang.psi.declarations.LSFComponentStubDeclaration"
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFComponentStubDeclarationImpl"
    stubClass = "com.lsfusion.lang.psi.stubs.ComponentStubElement"
    elementTypeFactory = "com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
}

componentDecl ::= multiCompoundID
{
    implements="com.lsfusion.lang.psi.declarations.LSFComponentDeclaration"
    mixin="com.lsfusion.lang.psi.declarations.impl.LSFComponentDeclarationImpl"
}

componentUsage ::= multiCompoundID
{
    implements="com.lsfusion.lang.psi.references.LSFComponentReference"
    mixin="com.lsfusion.lang.psi.references.impl.LSFComponentReferenceImpl"
}

propertySelector ::= formPropertyDrawUsage

setObjectPropertyStatement ::= ID EQUALS componentPropertyValue SEMI {pin = 2}

componentPropertyValue ::=  colorLiteral
                        |	stringLiteral
                        |	intLiteral
                        |	doubleLiteral
                        |	dimensionLiteral
                        |	booleanLiteral
                        |	boundsIntLiteral
                        |	boundsDoubleLiteral
                        |   containerTypeLiteral
                        |   flexAlignmentLiteral
                        |   formCalcPropertyObject

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////// META STATEMENT //////////////////////////////
////////////////////////////////////////////////////////////////////////////////

metaCodeDeclarationStatement ::= META simpleName LBRAC metaDeclIdList RBRAC anyTokens END {
    pin=2
    mixin = "com.lsfusion.lang.psi.declarations.impl.LSFMetaDeclarationImpl"
    implements = "com.lsfusion.lang.psi.declarations.LSFMetaDeclaration"
    stubClass = "com.lsfusion.lang.psi.stubs.MetaStubElement"
    elementTypeFactory = "com.lsfusion.lang.psi.stubs.types.LSFStubElementTypeFactory.create"
}

anyTokens ::= (<< readAny >>)*

private metaStatement ::= statement { recoverWhile = "meta_statement_recover" }
private meta_statement_recover ::= !(statement_start | RBRACE)
metaCodeBody ::= metaCodeBodyLeftBrace (metaStatement*) metaCodeBodyRightBrace

metaCodeBodyLeftBrace ::= LBRACE
metaCodeBodyRightBrace ::= RBRACE

metaCodeStatement ::= metaCodeStatementHeader metaCodeBody? metaCodeStatementSemi
{
    pin=2
    mixin="com.lsfusion.lang.psi.references.impl.LSFMetaReferenceImpl"
    implements="com.lsfusion.lang.psi.references.LSFMetaReference"
}

metaCodeStatementHeader ::= ATSIGN metacodeUsage LBRAC metaCodeIdList RBRAC
metaCodeStatementSemi ::= SEMI

metaDeclId ::=  ID
metaDeclIdList ::= (metaDeclId (COMMA metaDeclId)*)?

metaCodeIdList ::= (metaCodeId (COMMA metaCodeId)*)?

metaCodeId ::= (PRIMITIVE_TYPE | compoundID | metaCodeLiteral)?

metaCodeLiteral ::= LEX_STRING_LITERAL
                | 	LEX_UINT_LITERAL
                |	LEX_UNUMERIC_LITERAL
                |	LEX_UDOUBLE_LITERAL
                |	LEX_ULONG_LITERAL
                |	LEX_LOGICAL_LITERAL
                |	LEX_DATE_LITERAL
                |	LEX_DATETIME_LITERAL
                |	LEX_TIME_LITERAL
                |	LEX_COLOR_LITERAL
                |	NULL

////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////// COMMON /////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

emptyStatement ::= SEMI;

mappedPropertyClassParamDeclare ::= propertyUsageWrapper LBRAC classParamDeclareList RBRAC // temporary domain logic
{
    pin = 1
    implements = "com.lsfusion.lang.psi.context.PropertyUsageContext"
    methods = [ resolveParamClasses getParamList ]
}

propertyUsageWrapper ::= propertyUsage // for usages search filter

mappedPropertyExprParam ::= propertyUsage LBRAC exprParameterUsageList RBRAC // temporary mixed logic
{
    implements = "com.lsfusion.lang.psi.context.PropertyUsageContext"
    methods = [ resolveParamClasses getParamList]
}

simpleNameWithCaption ::= simpleName (stringLiteral)?

// local

objectUsageList ::= (nonEmptyObjectUsageList)?
nonEmptyObjectUsageList ::= objectUsage (COMMA objectUsage)*

nonEmptyGroupObjectUsageList ::= groupObjectUsage (COMMA groupObjectUsage)*

// global
nonEmptyCustomClassUsageList ::= customClassUsage (COMMA customClassUsage)*  { pin(".*") = 1}

nonEmptyModuleUsageList ::= moduleUsage (COMMA moduleUsage)* { pin(".*") = 1}

nonEmptyNamespaceUsageList ::= namespaceUsage (COMMA namespaceUsage)*  { pin(".*") = 1}

classNameList ::= (nonEmptyClassNameList)?
nonEmptyClassNameList ::= className (COMMA className)* { pin(".*") = 1}

nonEmptyPropertyUsageList ::= propertyUsage (COMMA propertyUsage)*  { pin(".*") = 1}

nonEmptyNoContextPropertyUsageList ::= noContextPropertyUsage (COMMA noContextPropertyUsage)*  { pin(".*") = 1}

nonEmptyFormUsageList ::= formUsage (COMMA formUsage)*  { pin(".*") = 1}

exprParameterUsageList ::= (exprParameterUsage (COMMA exprParameterUsage)*)? { pin(".*") = 1}

nonEmptyActionPDBList ::= actionPropertyDefinitionBody (COMMA actionPropertyDefinitionBody)* { pin(".*") = 1}

propertyExpressionList ::= (nonEmptyPropertyExpressionList)?
nonEmptyPropertyExpressionList ::= propertyExpression (COMMA propertyExpression)* { pin(".*") = 1}

literal ::=
        ulongLiteral
	|	uintLiteral
	|	udoubleLiteral
	|	unumericLiteral
	|	stringLiteral
	|	booleanLiteral
	|	dateTimeLiteral
	|	dateLiteral
	|	timeLiteral
	|	nullLiteral
	|	staticObjectID
	|	colorLiteral
{implements = "com.lsfusion.lang.psi.context.LSFExpression" methods = [ resolveInferredValueClass inferParamClasses getValueClassNames getValuePropertyNames ]}

builtInClassName ::= PRIMITIVE_TYPE
{
    mixin="com.lsfusion.lang.psi.LSFIdImpl"
    implements="com.lsfusion.lang.psi.LSFId"
}

className ::= builtInClassName | customClassUsage

// local

// parameterUsage is not needed yet, there is either declaration (mappedPropertyParamDeclare), or exprUsage (exprParameterUsage) 

objectUsage ::= simpleName
{mixin="com.lsfusion.lang.psi.references.impl.LSFObjectReferenceImpl" implements="com.lsfusion.lang.psi.references.LSFObjectReference"}

groupObjectUsage ::= simpleName
{mixin="com.lsfusion.lang.psi.references.impl.LSFGroupObjectReferenceImpl" implements="com.lsfusion.lang.psi.references.LSFGroupObjectReference"}

exprParameterNameUsage ::= classParamDeclare
{mixin="com.lsfusion.lang.psi.references.impl.LSFExprParamReferenceImpl" implements="com.lsfusion.lang.psi.references.LSFExprParamReference"}

// can be used for param and object simultaneously, for use in exprs
exprParameterUsage ::= ((DOLLAR)? exprParameterNameUsage) | (DOLLAR LEX_UINT_LITERAL)

// global

customClassUsage ::= compoundID
{mixin="com.lsfusion.lang.psi.references.impl.LSFClassReferenceImpl" implements="com.lsfusion.lang.psi.references.LSFClassReference"}

moduleUsage ::= simpleName
{mixin="com.lsfusion.lang.psi.references.impl.LSFModuleReferenceImpl" implements="com.lsfusion.lang.psi.references.LSFModuleReference"}

namespaceUsage ::= simpleName
{mixin="com.lsfusion.lang.psi.references.impl.LSFNamespaceReferenceImpl" implements="com.lsfusion.lang.psi.references.LSFNamespaceReference"}

explicitPropClass ::= className | QUESTION 

nonEmptyExplicitPropClassList ::= explicitPropClass (COMMA explicitPropClass)*
emptyExplicitPropClassList ::= nonEmptyExplicitPropClassList?
explicitPropClassUsage ::= LSQBR emptyExplicitPropClassList RSQBR
propertyUsage ::= compoundID explicitPropClassUsage?
{mixin="com.lsfusion.lang.psi.references.impl.LSFPropReferenceImpl" implements="com.lsfusion.lang.psi.references.LSFPropReference"}

tableUsage ::= compoundID
{mixin="com.lsfusion.lang.psi.references.impl.LSFTableReferenceImpl" implements="com.lsfusion.lang.psi.references.LSFTableReference"}

groupUsage ::= compoundID
{mixin="com.lsfusion.lang.psi.references.impl.LSFGroupReferenceImpl" implements="com.lsfusion.lang.psi.references.LSFGroupReference"}

formUsage ::= compoundID
{mixin="com.lsfusion.lang.psi.references.impl.LSFFormReferenceImpl" implements="com.lsfusion.lang.psi.references.LSFFormReference"}

windowUsage ::= compoundID
{mixin="com.lsfusion.lang.psi.references.impl.LSFWindowReferenceImpl" implements="com.lsfusion.lang.psi.references.LSFWindowReference"}

navigatorElementUsage ::= compoundID
{mixin="com.lsfusion.lang.psi.references.impl.LSFNavigatorElementReferenceImpl" implements="com.lsfusion.lang.psi.references.LSFNavigatorElementReference"}

metacodeUsage ::= compoundID

typeId ::= PRIMITIVE_TYPE | OBJECT

compoundID ::= (<<innerIDStop>> namespaceUsage POINT simpleName) | simpleName

staticObjectID ::= <<fullCompoundParamDeclareStop>> <<innerIDCheck>> customClassUsage POINT simpleName
{mixin="com.lsfusion.lang.psi.references.impl.LSFStaticObjectReferenceImpl" implements="com.lsfusion.lang.psi.references.LSFStaticObjectReference"}

groupObjectID ::= <<innerIDCheck>> formUsage POINT groupObjectUsage
{
    pin = 3
    implements="com.lsfusion.lang.psi.context.FormContext"
    methods = [resolveFormDecl]
}

objectID ::= <<innerIDCheck>> formUsage POINT objectUsage
{
    pin = 3
    implements="com.lsfusion.lang.psi.context.FormContext"
    methods = [resolveFormDecl]
}

formPropertyDrawID ::= <<innerIDCheck>> formUsage POINT formPropertyDrawUsage
{
    pin = 3
    implements="com.lsfusion.lang.psi.context.FormContext"
    methods = [resolveFormDecl]
}

multiCompoundID ::= ID (POINT ID)*
{
    mixin="com.lsfusion.lang.psi.LSFIdImpl"
    implements="com.lsfusion.lang.psi.LSFId"
}

exclusiveOverrideOption ::= OVERRIDE | EXCLUSIVE

colorLiteral ::= LEX_COLOR_LITERAL | (RGB LBRAC uintLiteral COMMA uintLiteral COMMA uintLiteral RBRAC)
stringLiteral ::= LEX_STRING_LITERAL
{
    mixin="com.lsfusion.lang.psi.LSFStringValueLiteralImpl"
    implements="com.lsfusion.lang.psi.LSFStringValueLiteral"
}
intLiteral ::= (MINUS)? uintLiteral
longLiteral ::=  (MINUS)? ulongLiteral
doubleLiteral ::= (MINUS)? unumericLiteral
dateLiteral ::= LEX_DATE_LITERAL
dateTimeLiteral ::= LEX_DATETIME_LITERAL
timeLiteral ::= LEX_TIME_LITERAL
booleanLiteral ::= LEX_LOGICAL_LITERAL
udoubleLiteral ::= LEX_UDOUBLE_LITERAL
unumericLiteral ::= LEX_UNUMERIC_LITERAL
uintLiteral ::= LEX_UINT_LITERAL
ulongLiteral ::= LEX_ULONG_LITERAL
nullLiteral ::= NULL

nullOption ::= NULL

dimensionLiteral ::= LBRAC intLiteral COMMA intLiteral RBRAC
boundsIntLiteral ::= LBRAC intLiteral COMMA intLiteral COMMA intLiteral COMMA intLiteral RBRAC
boundsDoubleLiteral ::= LBRAC doubleLiteral COMMA doubleLiteral COMMA doubleLiteral COMMA doubleLiteral RBRAC

insertRelativePositionLiteral ::= BEFORE | AFTER

containerTypeLiteral ::=    CONTAINERV
	                    |	CONTAINERH
	                    |	COLUMNS
	                    |	TABBED
	                    |	SPLITH
	                    |	SPLITV
	                    
alignmentLiteral ::= LEADING | CENTER | TRAILING

flexAlignmentLiteral ::= LEADING | CENTER | TRAILING | STRETCH

modalityTypeLiteral ::= DOCKED | MODAL | DOCKEDMODAL | FULLSCREEN | DIALOG

formPrintTypeLiteral ::= PRINT (AUTO | XLS | PDF)? {pin = 1}

formSessionScopeLiteral ::= OLDSESSION | NEWSESSION | MANAGESESSION | NESTEDSESSION

emailRecipientTypeLiteral ::= TO | CC | BCC

emailAttachFormat ::= PDF | DOCX | HTML | RTF

